name: conda-py3.7
channels:
- conda-forge
dependencies:
- python=3.7
- arabic_reshaper
- astunparse
- backports
- codecov
- coveralls
- distro
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- imageio
- imageio-ffmpeg
- javascripthon
- jedi
- json_tricks
- lxml
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip!=19.0,!=19.0.1,!=19.0.2
- psutil
- pyglet>=1.4.9
- glfw!=3.3.1
- pyglfw
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytables
- attrs
- pytest
- pytest-cov
- python-bidi
- python-gitlab
- python-sounddevice
- pyyaml
- pyzmq
- questplus >=2019.3
- requests
- scipy
- wheel
- wxpython
- xlrd
- pip
- pip:
  - pygame
  - pyo
  - pyparallel
